fos_elastica:
    clients:
        default: { host: '%env(resolve:es_host)%', port: '%env(resolve:es_port)%' }
    indexes:
        app:
            use_alias: true
            types:
                api_request_log:
                    properties:
                        longitude: ~
                        latitude: ~
                        user: ~
                    persistence:
                        driver: orm
                        model: App\Entity\ApiRequest\ApiRequestLog
