- name: set permissions for log dir
  shell: chmod -R 777 log
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/var"
- name: set permissions for cache dir
  shell: chmod -R 777 cache
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/var"
- name: set permissions for cache/prod dir
  shell: chmod -R 777 prod
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/var/cache"
- name: Create DB if not exists
  command: '{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}/{{ symfony_console_path }} doctrine:database:create --if-not-exists --env=prod'
- name: Migrate DB
  command: '{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}/{{ symfony_console_path }} doctrine:migrations:migrate --no-interaction --allow-no-migration'